### ISSUE TITLE
Problem running /veins_carla_run

### ISSUE THREAD

**Issue by atanas1054** [veins/veins_carla#1]
Hello,

Thank you for the repository. I followed all the prerequisites and installed/compiled OMNeT++ 6, Veins, Veins_Carla and Carla 9.12. However when I run 

`cd veins_carla/examples/veins_carla
./doRun.sh`

I get the following error:

`OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0.1, build: 220831-e4f07d04b8, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer
Setting up Qtenv...
Loading NED files from ../../../veins/src/veins:  43
Loading NED files from ../../src/veins_carla: 
<!> Error: Could not load NED sources from '../../src/veins_carla': Declared package 'veins_carla.app' does not match expected package 'app' in file ExampleCarlaApplication.ned`

I can run the example from veins but not the veins_carla example. Any help will be appreciated.

**Comment by Xuezhenggdut** [comment]
ubuntu18.04；CARLA0.9.12；UE4.26；OMNet++5.6.2；SUMO-1.8.0；I can run the example from veins, but I encounter the same bug when trying the veins_carla example. Is it related to the version?

![image](https://github.com/veins/veins_carla/assets/46556712/fb073f80-8990-4f70-8531-b7b449223a2a)

**Comment by FouziBoukhalfa** [comment]
Hi,
I am facing the same issue, is there any solution for this?

Best regards,
Fouzi

**Comment by Xuezhenggdut** [comment]
Hi Fouzi,
I have previously reached out to Tobias Hardes in an attempt to address this issue, but unfortunately, we have not been able to find a solution. Currently, we are in the process of waiting for his hardware testing to be conducted as part of the troubleshooting process. However, the wait has been longer than expected, and I believe that a gentle reminder from your end could help expedite the resolution process.
Best regards,
Zheng Xue

&nbsp;


xuezhenggdut
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月23日(星期一) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [veins/veins_carla] Problem running /veins_carla_run (Issue #1)





 
Hi,
 I am facing the same issue, is there any solution for this?
 
Best regards,
 Fouzi
